music-encoding/music-encoding.github.io

resources/bibliography.md
This PR cleans up the MEI bibliography: http://music-encoding.org/resources/bibliography.html
Beside fixing typos and errors in bibliographical information and harmonizing the formatting, the changes requested include the following:
- provide stable and working (for now) links to papers whenever possible
- use global identifier (doi, urn) whenever possible
- point out the selectiveness of the list in the title
...
[ongoing]
fixes #11
=> Clean up bibliography

resources/mei_bibliography.bib
This removes links to pdf files behind paywalls. Also one doubled doi link is removed.
=> Removing broken links to acm.org

_sass/mei.scss
This commit fixes the dark grey highlight colour by changing it to a lighter shade of grey.
Fixes music-encoding/music-encoding.github.io#16
=> Fixed: Gray highlight striping

conference/past.md
This PR updates the past conferences to include the 2018 program, and removes a duplicate one for Tours.
=> Update past conferences

_sass/spectre/_toasts.scss
Removes width attribute for toast to have it fixed at the top again. 
(We should discuss a better, more responsive approach in Oxford)
=> removed 100% from toast

resources/mei_bibliography.bib
This small PR cleans up the bibfile for MEI bibliography a bit by doing the following:
- fix some typos and formatting for 2017 publications
- add abstracts and links to PDF where possible
=> fix 2017 publications in bibliography

README.md, resources/schemas.md
This small PR adds a link to the MEI guidelines repository to provide information on how to contribute and on how to run the website locally for development. 
It also adds a link from schemas page to the comparison page for the MEI 4.0 schema. In passing it fixes a broken link in schemas.md to the MEI ALL schema.
Fixes #51 
Fixes #53
=> Update readme & schemas.md

_config.yml, community/community-contacts.md
Also redirects from the old mailing list page to the new community contacts page.
=> Fixed: Add community contacts page

_sass/_specs.scss
Font weights < 400 make the text in the specs quite light. We also do not load all the possible font weights (`https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro`) so just setting label weights to `bold` should be fine.
I have also condensed the variables into SASS variables.
=> Fix font weights in specs

_layouts/tutorials.html, _tutorials/199_tutorials/writingTutorials-06.html
This PR adds some more information to the tutorial entry page. It adds a paragraph about writing tutorials and where to find a list of missing tutorials. It also adds external tutorials and training material related to MEI.
=> Tutorials: Add more information to tutorial entry page

_layouts/tutorials.html, resources/tutorials.md
This PR changes the style for the bibbase generated list of external tutorials on the Tutorials entry page from default to `side` which is more compact.
It also moves the content of the page from `_layout/tutorials.html` to the corresponding `resource/tutorials.md` file, which is then called from the html file via `{{ content }}`
=> style(tutorials): use theme=side for bibbase style and move content to md file

_config.yml, about/index.md, resources/background.md
This PR addresses #105 . 
It changes the title of the "Introduction to MEI" subpage under `Resources` to "Background" and removes the "intro to mei" section there that mostly doubled the beginning of the "About" page. 
Detail information that was not included in the "About" page so far, has been moved there. The PR also sligthly restructures the order of the "About" page's first paragraph.
Closes #105.
=> enhance: Intro to MEI

_posts/2020-05-23-digital-humanities-series-sessionII.md
Digital Humanities in Early Music Research I, Session II: Early Music Databases and Encoding to be held in June 2020.
=> Add announcement of event.

_layouts/tutorials.html, js/mei-tutorials.js
This PR proposes some light refactorings for tutorials.js, including
- handling of step number incrementation
- removing redundant calls and simplifying functions
- improving messages ( fixes #138 ) and 
- refactoring variable names for consistency 
It also adds another log if a stepNumber is thrown with a value of NaN to improve debugging of #136 .
=> Little refactorings for tutorial.js

_conferences/2013/index.html, _conferences/2014/index.html, _conferences/2015/index.html, _conferences/2016/index.html, _conferences/2017/index.html, _conferences/2018/index.html, _conferences/2019/index.html, _conferences/2020/index.html, _conferences/2021/index.html, _config.yml, _layouts/conference.html
As discussed in #162 , this PR removes the `future:true` option introduced in https://github.com/music-encoding/music-encoding.github.io/pull/163/commits/eaeb9ee6af7824d58e93b3b9e9eb3ca6432ea20f.
Instead, `future:false` (Jekyll's default) is used, so that post messages are intuitively posted only at their specified time without any need for additional options. 
The front matter of the conference index files now uses `date-start` instead of `date` for the start date of the conference, so it is not affected by Jekylls internal blog-specific date handling. Thus, future conferences will show up if needed. 
If it is necessary to hide (recent or future) conference files, it is possible to use the option `published: false` in the front matter of that file individually.
=> Remove global future:true option

_layouts/conference.html, _sass/mei.scss
This PR fixes the wrong padding on pages with bib-base inclusion as mentioned in #140. 
Due to bootstrap involvement, these pages get an additional `padding-left:20px; padding-right:20px`, which is removed here by applying `padding-left:inherit; padding-right:inherit` on the `body` element. No side effects have been observed, all pages are displayed as expected. 
Additionally, this PR changes the content width of the conference section on small devices from `col-sm-11` to full-width `col-sm-12` (similar to other contents).
Fixes #140
=> Style improvements

_layouts/conference.html
This PR fixes the dropdown menu issue on small devices (Safari) described in #149 .
It adds a `tabindex="1"` to the anchor tag in the conference submenu dropdown. 
Solution found here: https://github.com/picturepan2/spectre/issues/154
Fixes #149
=> Fix dropdown menu issue on small devices (Safari)

resources/mei_bibliography.bib
Issue with Rizo and Marsden (2019) entry in the [website's bibliography](https://music-encoding.org/resources/bibliography.html ). The title was wrong, it was actually the one from Devaney and Léveillé (2019). It has been corrected now to "An MEI-based standard encoding for hierarchical music analysis."
=> Fix title for Rizo's entry

_conferences/2013/committee.html, _conferences/2014/committee.html, _conferences/2015/committee.html, _conferences/2016/committee.html, _conferences/2017/committee.html
The 'organizers' section is on the side menu, it includes entries for the local organizing committee and the program committee. This is just for the conferences that do not have images (2013–2017), the others (2018–2020) already include this information in the call for proposals.
=> Add 'organizers' section for past conferences.

conference/past.md
This PR adds a filter to the `past.md` template to show only events that have a past `date-end` in their header, removing future events. 
It follows the approach described here: https://maedi.com/code/filter-by-date/
Fixes #178
=> Filter upcoming conference from past conferences overview

_posts/2020-12-18-MEC2021-update..md
While announcing the postponed MEC on the conference page itself, we missed to add a news post on the front page (thanks @kepper for pointing out).
This PR adds the news post.
=> Add missing news post for postponed MEC2021

_layouts/tools.html
Short one line postscript PR for #203
Missed to add the side menu entry for meico on the tools site (we should have this automated in the future, cf. #130 )
=> fix(tools): add side menu entry for meico

archive/index.md
This PR contributes to #131 by redirecting the archive's conference section to the conference subpage (previous programs and proceedings are listed there now).
=> fix(archive): redirect conference programs & proceedings

_includes/menu-accordion.html
Sorry, missed that one in #215, since it is embedded in a mixture of html and jekyll liquids here: https://github.com/music-encoding/music-encoding.github.io/blob/master/_includes/menu-accordion.html#L26-L30
UL cannot be directly nested into another UL, but only as a child of LI (cf. https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#nesting_lists).
@bwbohl Could you please double-check for any potential CSS issues?
=> Fix invalid or obsolete HTML (post scriptum)

_conferences/2020/code-of-conduct.html
Just a very small PR to reintegrate the Code of Conduct in the MEC2020 pages. It was somehow removed, but is referenced from the MEC2020 index page.
=> fix(conference): reintegrate MEC2020 Code of Conduct

_conferences/2021/call.html, _conferences/2021/people.html
As an addendum for #221, this small PR updates affiliations and entries for keynote speakers and members of the PC team.
=> MEC2021: update affiliations and PC team

_posts/2021-06-15-mec2021-programme.md, _posts/2021-06-15-teaching-music-history-session.md, _posts/2021-07-27-music-encoding-use-cases-in-us-libraries.md
This PR adds the latest events to news including
1) Today's music encoding related session at Teaching Music History Conference 2021 (sorry for the delay)
2) the updated program website for MEC2021
3) the "Music Encoding Use-cases in U.S. Libraries" session at IAML/DLfM (will be posted on 27 June)
=> Add latest events to news

_conferences/2021/program.html
This small PR adds the titles of the keynotes, switches keynote order according to the conference schedule, and adds Ana Llorens as co-author. It also updates some poster titles that had changed after revision.
@davidrizo Could you please have a look?
=> Update conference program

archive/index.md, resources/schemas.md
This PR contributes to #131 by redirecting the archive's "Previous versions of MEI" section to the schema and namespace subpage (previous versions are listed there now).
=> fix(archive): redirect previous MEI versions to schema page

_conferences/2021/keynotes.html
This PR adds a keynote page to the MEC 2021 conference section with the embedded video of the opening keynote.
=> feat(conference): add keynote videos for MEC2021

conference/mec_proceedings.bib, conference/proceedings.md
This PR adds bib files for the MEC 2021 proceedings to be listed on the website.
Output can be checked here for now: https://musicenfanthen.github.io/bibbase-test/
@davidrizo Can you have a look please?
=> feat(conference): add mec 2021 proceedings

community/technical-team.md
This PR moves the info about ODD meetings from the (deprecated) Wiki to the Technical Team page. 
It also fixes a minor layout issue on the TT page.
Fixes #338
=> Update technical team page

_posts/2019-05-31-mei-basic-first-draft.md
This PR fixes the broken link to the MEI basic branch reported by the link checker (in post "First Draft of MEI Basic", May 31, 2019). The branch was merged to `develop` in 2020 already, but the branch itself was deleted only 20 days ago ( music-encoding/music-encoding#584). That is why the link checker only now throws an error, since the branch is not available anymore for reference. 
With this PR, the post now links to the latest commit of the basic branch that was available at the time of the post.
Addresses one part of #335
=> fix(posts): fix broken link to MEI basic branch

resources/tutorials.md
This PR removes the separate bibliography from the tutorials landing page and instead points to the list of training material on the pedagogy resources page.
Fixes #341
=> fix(tutorials): link from tutorials to pedagogy resources

.github/dependabot.yml, .github/workflows/link-checker.yml
This PR pins the versin of the markdown-link-checker to v1 (which uses an older pinned version of the underlying upstream markdown-link-checker [mlc] that should not throw false positives 🤞 ). It also adds a dependabot.yml to notify about available updates of the gh-actions dependencies.
=> fix(gh-actions): pin of markdown-link-check action + dependabot

README.md
This PR adds a little badge to indicate build jekyll status and another one for the license.
=> Add jekyll and license badges

.gitignore
This PR adds the automatically generated ,jekyll-cache folder to gitignore to prevent it from being commited.
=> fix(build): add .jekyll-cache to gitignore

.github/workflows/jekyll.yml
This PR prevents the jekyll build action from running on forks which is not needed.
=> fix(gh-action): run jekyll action only on main repo

.github/workflows/link-checker.yml, _conferences/2022/bursariesChildcare.html, _conferences/2022/bursariesStudent.html
This PR fixes the latest broken link to Dalhousie's diversity policy in the MEC2022 pages.
It also removes the "fail fast" option from the link checker because that option prevented the creation of issues.
=> fix(conferences): fix broken diversity link

lychee.toml
Some days ago, lychee changed its implementation of the verbosity option. It does not accept boolean values any more, but expects one of the accepted log levels: "error", "warn", "info", "debug", or "trace".
Fixes #440
=> fix(ci): fix verbosity level

_layouts/tutorials-ES.html, _tutorials-ES/103_chords/step-01/103_chords_step-01-desc.html, _tutorials-ES/103_chords/step-02/103_chords_step-02-desc.html, js/mei-tutorials.js
This PR adds a (extendable) mechanism to translate the yet untranslated strings from the tutorial's JS and HTML file. In this sense, it complements the PR #436  .
=> feat(tutorials): add mechanism to translate strings from js file

.github/workflows/jekyll.yml, .github/workflows/link-checker.yml
This PR replaces version tags with their SHA-1 representation for all 3rd party actions used in the GH actions workflows. Github's own actions (starting with `action/...`) are not transformed.
For pinning the SHA-1, I used ratchet: https://github.com/sethvargo/ratchet . The tool can be run from CLI, CI or docker and provides easy methods to check for, pin or unpin tags and SHA-1's in a workflow.
Fixes #467
=> ci(gh-actions): use pinned SHA-1 instead of version tag for 3rd party actions

lychee.toml
This PR adjusts the exclusion of the no longer existing MEC '22 conftool page in the lychee config file. Instead of using the full path of the broken link, it uses a wildcard. At least locally, this throws no error anymore.
Fixes #477 
Fixes #475 
Fixes #474
=> fix(lychee): use a wildcard for 2022 conftool page

_posts/2023-09-01-mec2022-proceedings-published.md
This PR adds a news post about the MEC2022 proceedings (dated back to the day of annoucement).
=> Add proceedings post

_posts/2023-10-06-ig-pedagogy-roundtable-published.md
This PR adds a news post about the roundtable publication of members of the Digital Pedagogy IG.
=> Add roundtable post

_posts/2023-09-01-mec2022-proceedings-published.md
This PR fixes the links in the proceedings post added in #521. Markdown syntax for links was missing.
=> Fix markdown for proceedings links

resources/schemas.md
This PR adds a link to the PDF to the MEI Namespace and Schemas page (PDFs from previous versions are available from there, too).
=> Add link to PDF

_conferences/2024/call.html
This PR fixes the markdown syntax for the conftool link inside the html file for the CfP introduced in #539 
It also secures the target blank links a bit.
=> Update call.html (II)

_layouts/tutorials-ES.html, _layouts/tutorials.html, js/mei-tutorials.js
This PR adds functionality for a back button to the tutorials. It mutes the button if there is no previous step. It also prevents both buttons from being displayed before the tutorial step gets loaded. 
The PR therefore reorganizes and restructures a bit of the logic of the tutorials' JS file. 
Fixes #464 
Screenshots:
=> feat(tutorials): add a back button for the tutorial steps

.github/workflows/link-checker.yml
In #575, Xitter was excluded from the lycheeverse action. However, issues like #577 were raised from broken link checker action. This PR adds the exclusion keywords in that action.
Fixes #577
=> fix: exclude xitter from broken link checker

community/technical-team.md
This PR updates the schedule for the ODD meetings on the technical team page.
Only exception from our LAST thursday/friday principle is in March, since the last Friday is Good Friday, and thus a holiday in some regions.
=> fix: update time schedule for ODD meetings

conference/past.md
For conference logos that refer to externally hosted images the current processing outputs malformed URLs like `https://music-encoding.org/images/https://teimec2023.uni-paderborn.de/assets/img/logo-full-encoding-cultures.png`.
This PR introduces a check for `://` that will bypass the default string operation to create the image link and simply output the URL as it is given in the conference yaml file.
=> add conditional for external URLs

conference/past.md
This PR reduces the size of the placeholder headers on the past conferences page (from h1 to h3, since they should not have the same size as the page title.)
Also, indents the fluid commands of the recently added image conditional.
=> conferences: minor layout patch

.github/dependabot.yml, .github/workflows/jekyll.yml, .github/workflows/link-checker.yml
This PR adds some best practice security hardenings to the repo's actions workflows. This includes referencing commit shas of the used action versions, setting minimal permissions and automatic dependency updates.
=> ci(gh-actions): harden actions

js/mei-tutorials.js
As laid out in #617, it's better to use a key string first, language string second approach for the tutorialStrings mapping. This will make it easier to add new languages or new strings in the future.
Fixes #617
=> fix(tutorials): switch access order of language strings

_layouts/tutorials-ES.html, _layouts/tutorials.html
This PR adds a back button to the tutorials main page on the single tutorials sub pages.
Fixes #641
=> fix(tutorials): add back button to tutorials main page

community/community-contacts.md, resources/pedagogy.md
Updated text to reflect new name. Humanities Commons is now Knowledge Commons.
=> Updated name of repository

community/mei-board.md
This PR removes the non-current board term 2021-2023 from the current term section.
=> community: remove non-current board term

community/mei-board.md
This PR adds missing board members from previous terms.
=> community: update previous board members

_posts/2024-10-25-call-for-nominations.md
This PR adds the Call for Nominations for the 2024 MEI election to the news page
Currently a draft PR to prevent accidental merging until Oct 25, 2024 (start of nominations phase)
=> Add 2024 Call for Nominations

conference/proceedings.md
This PR activates the 2024 proceedings which was forgotten in #707.
It also simplifies the logic for the proceedings html by looping over the publication periods instead of repeating the html for every period.
=> fix(proceedings): activate proceedings

_conferences/2025/01_index.html, _conferences/2025/02_call.html
New and final deadline extension to 20 December 2024
=> MEC 2025: Announce CfP deadline extension

_posts/2025-01-16-mei-board-meetings, community/mei-board/protocols/2025-01-07_Virtual-Board-Meeting.md
Public meeting notes to be added to the [MEI Board webpage](https://music-encoding.org/community/mei-board.html)
=> board: add public meeting notes for January 7, 2025

.github/workflows/jekyll.yml
This PR udpates the ruby version to 3.2 to fix a build error.
=> fix: update ruby version

_conferences/2025/02_call.html
Updated PC members.
Currently, I can't test the site locally on my machine or within a Docker container. Theoretically, this commit should not create a problem. How is the current website situation? Is it safe to merge?
=> MEC 2025: Update Programme Committee

community/mei-board.md
This PR includes a small follow-up to #725 by adding the .html suffix to the protocol links. So the actual change was from .md suffixes to .html, thus making the links available on the website and (hopefully) fixing the broken link checker.
=> docs: fix protocol links (again)

Gemfile.lock
As a small follow-up for #750, this PR adds some missing OS-specific dependencies that had not been properly resolved there.
=> fix: add missing os-specific native extensions in Gemfile.lock

archive/resources/js/main.js
This PR fixes the rendering of the pie charts on the schema comparison page. 
The macro groups and datatypes pie charts did not show up after the updates in music-encoding/music-encoding#1510. This PR transfers the changes to the js file there to the repo here.
Before:
After:
=> fix(comparison): fix js to display refactored macros

community/mei-board/protocols/2025-03-03_Virtual-Board-Meeting.md, community/mei-board/protocols/2025-04-07_Virtual-Board-Meeting.md
This PR fixes some of the protocols not showing up due to an empty line at the beginning of the file.
It also adds markdown syntax for the links to socials.
=> board: fix protocols

conference/mec_proceedings.bib
After I accidentally merged #798 instead of annplaksin#1 I reverted with #799 
Now, this is the PR including the fixes of the BibTeX generously provided by @musicEnfanthen ...
Apologies for the mess!
(And I will prevent any further mess by avoiding to merge this myself... and hopefully not again just by accident 😓 )
=> Add fixed MEC 2025 abstracts to BibTeX

_conferences/2026/06_call.html
This PR fixes some minor stuff in the HTML formatting of the CfP.
=> conference: fix blank space and update link reference

_conferences/2026/06_call.html
- Added a table of contents at the top of the CfP for navigation
- Made the deadline bold
- Anna Plaksin was listed as chair (and in the e-mail – sorry, Anna)
- Update a few 2025s still in the updated call (thanks to Ich for pointing these out)
=> conference: CfP ToC, formatting tweak, removing Anna P's chair role
