resources/bibliography.md

This brief addition to PR #12 adds the french literature proposed in #11 and removes the entry from 2006 mentioned there, too.

Bibliography additions

---

_sass/mei.scss

Problem visible on the [projects page](http://music-encoding.org/community/projects-users.html) with narrower browser windows.

Prevent images in cards to overflow

---

resources/mei_bibliography.bib

This PR adds several recent bibliography items that were missing.

New Bibliography Items

---

_includes/header.html
_includes/menu.html
_layouts/default.html
index.html

Basically fixes the same errors as in the guidelines.

fixing errors

---

_config.yml
resources/schemas.md

Add a page for schemas and namespaces

---

_layouts/tools.html
community/technical-team.md

* removes MEISE from index on tool page
* fixes a typo

minor fixes

---

_sass/_specs.scss
_sass/mei.scss

this goes along with the improve-spec-extraction branch on the guidelines repo

adding css for new guidelines version

---

resources/mei_bibliography.bib

This PR updates the bib file for the MEI bibliography with the latest articles of "International Journal on Digital Libraries"

bibliography: update bib file

---

resources/mei_bibliography.bib

Sorry, I just recognized that I forgot the publication year for both entries added in #75

bibliography: add year of publication for new entries

---

_tutorials/102_march/step-01/102_march_step-01-desc.html
_tutorials/102_march/step-01/102_march_step-01-desc_test_change.html
_tutorials/102_march/step-02/102_march_step-02-desc.html
_tutorials/102_march/step-03/102_march_step-03-desc.html
_tutorials/102_march/step-04/102_march_step-04-desc.html
_tutorials/102_march/step-05/102_march_step-05-desc.html
_tutorials/102_march/step-06/102_march_step-06-desc.html
_tutorials/102_march/step-07/102_march_step-07-desc.html
_tutorials/102_march/step-08/102_march_step-08-desc.html
_tutorials/102_march/step-09/102_march_step-09-desc.html
_tutorials/102_march/step-10/102_march_step-10-desc.html
_tutorials/102_march/step-11/102_march_step-11-desc.html
_tutorials/102_march/step-12/102_march_step-12-desc.html

Change in language, please review.

Tutorial in progress

---

_tutorials/104_rests/104_rests.json
_tutorials/104_rests/104_rests_end.html
_tutorials/104_rests/104_rests_step-00-desc.html
_tutorials/104_rests/104_rests_step-01-desc.html
_tutorials/104_rests/104_rests_step-04-desc.html
_tutorials/104_rests/104_rests_step-04-prefill.xml
_tutorials/104_rests/104_rests_step-04.xml

This PR adds some fixes and clarifications to the new 104 rests tutorial in terms of a belated review. Esp. step 4 (spaces) went through some clarification since the task there was not clear enough for beginner users.

Tutorials: Review new 104 rests tutorial

---

_tutorials/101_quickstart/101_quickstart_end.html
_tutorials/101_quickstart/101_quickstart_step-01-desc.html
_tutorials/103_chords/103_chords_end.html

This mini PR interlinks the tutorials a little bit more and fixes some links.

Tutorials: add some more interlinking between tutorials 

---

_posts/2019-05-31-mei-basic-first-draft.md
downloads/Chopin_Etude_op.10_no.9_basic.mei
downloads/mei-basic_2019-05-31_184d45b.rng
downloads/mei-basic_2019-05-31_184d45b.xml

news post introducing MEI Basic

news post for MEI Basic

---

_config.yml
_layouts/sidebar.html
conference/2019/program.html

This mini PR adds the tutorials to Jekylls config.yml, so they will become visible on the live website.
Also, it reverts minor reversions that happened during tutorial merge into master, we apologize for that!

Tutorials: Publish on website

---

_posts/2019-08-28-registration-nashville.md

...schedule will follow shortly in another post. Thanks!

Added post for workshop registration

---

archive/index.md

This pull request adds version 3 to Previous Versions of MEI in Archive section of the website. Fixes #95

Add version 3 to Previous Versions of MEI in Archive section of the website.

---

resources/tools.md

Addition of the Music Sheet Viewer WordPress plugin

Addition of the Music Sheet Viewer

---

resources/schemas.md

This PR addresses #98 .
It changes the order of mentioned schemas and adds some information about the purpose and possible use cases of `MEI All` and `MEI All (Any Start Element)` as well as about possibilities of further customizations.
Fixes #98

Add schema recommendation & customization

---

community/community-contacts.md

Add information about the "Humanities Commons - MEI Group," a new channel to attract more scholars to MEI which was recently created by Anna Kijas. This is another channel of communication (in addition to the mailing-list and slack).

Add entry into Community Contacts page

---

community/mei-board.md
community/mei-board/protocols/2020-03-25_Virtual-Board-Meeting.md

Updating Board Minutes (March)

---

_sass/_specs.scss
_sass/mei.scss

this PR provides CSS for music-encoding/guidelines#170. All that needs to be known is mentioned there. Both PRs depend on each other…

responsive layout for guidelines

---

_includes/header.html
_includes/menu-accordion.html
_layouts/tutorials.html
_sass/_specs.scss
_sass/mei.scss
community/projects-users.md
index.html

This PR focuses on making the current layout more responsive to accustom different screen sizes. Some general layout issues had to be resolved to achieve this, and some layout issues still remain:
* additional padding on the tutorials and bibliography subpages due to bootstrap involvement in the bib-base inclusion (see #140)

Improve general website responsive layout

---

_sass/mei.scss

fix layering problem where menu dropdowns would hide behind  startCarousel closes #143

fix menu and carousel layering

---

_sass/_specs.scss

goes along with https://github.com/music-encoding/guidelines/pull/181

remove 100vw

---

_sass/mei.scss

the submenu on the conference pages was layered above the navbar, fixed with this PR

fix navbar layering

---

_posts/2020-10-07-MEI-Metadata-meeting-update..md

Post on update for metadata meeting (now to be held online), requested by Kristina Richts. Ready for merge.

Add update for the metadata working meeting

---

resources/mei_bibliography.bib

This PR supplements the selected bibliography with MEI-related contributions from the recently published proceedings of the 2019 conference of the "Gesellschaft für Musikforschung" (GfM).

Bibliography: Add MEI related papers from GfM2019 proceedings

---

menus/dev/menu.html
menus/v3/menu.html
menus/v4/menu.html

this is necessary to set up the guidelines menus

Generate guidelines menu

---

community/mei-board.md
community/mei-board/protocols/2021-01-14_Virtual-Board-Meeting.md

Minutes for Board Meeting in January

Board minutes

---

resources/mei_bibliography.bib

This PR supplements the selected bibliography with the nota bene series volume 15 from the National Library of Norway edited inter alia by @margrethesb and the MEI-related contribution from @axgeertinger

Bibliography

---

_posts/2021-03-14-digital-humanities-in-early-music-research-omr.md

This PR adds a post about next week's MEI related OMR workshop at the Czech Academy of Sciences, Prague, to the news section of the website.

Add post for MEI related OMR workshop at CAS, Prague

---

_includes/menu-accordion.html
_layouts/projects.html
_layouts/tutorials.html
community/projects-users.md
conference/past.md
conference/proceedings.md
index.html

Inspired by @rettinghaus' findings in music-encoding/guidelines#47, I checked the HTML of the website with https://validator.w3.org/nu/ .
This PR fixes most of the errors and warnings identified by the W3C validator.

Fix invalid or obsolete HTML

---

_conferences/2021/bursaries.html
_conferences/2021/register.html
_conferences/2021/travel.html

Note about COVID added. Dates have been corrected

Last update before opening the registration

---

_conferences/2021/covid19.html
_conferences/2021/program.html
_conferences/2021/travel.html

A new COVID-19 information page has been added. Humdrum workshop has been edited by adding hyperlinks

COVID-19 information added. Workshops updated

---

resources/pedagogy.md

This is the new pages for pedagogical resources. This was proposed by the chairs of the Digital Pedagogy IG and it was approved in the last Board Meeting.

Pedagogy resources

---

_config.yml

This little PR includes the changes implemented in #231 in the config.yml file. Otherwise the page won't show up.

[HOTFIX] Include pedagogy page in yml file

---

_conferences/2021/program.html

Un-conference day program updated

MEC'21 program updated

---

_conferences/2021/program.html

This PR updates the public program website with infos about:
- workshop convenors
- session chairs
- meetings

MEC2021: Program update

---

_conferences/2021/program.html

Message about login. Paper title updated

Program updated

---

_conferences/2021/program.html

This small PR fixes wrong meeting dates in the program. Thanks to @annakijas1 for catching!

fix(program): fix meeting dates

---

_conferences/2021/people.html
_conferences/2021/program.html

MEC'21 program style corrections in Ana Llorens CV.
Personnel changed

MEC'21 program and people corrections

---

_posts/2021-07-16-by-laws-extension.md

This PR adds a post for the rfc extension to the MEI website news section.

update(posts): add post for rfc extension

---

community/mei-board.md
community/mei-board/protocols/2022-01-19_Virtual-Board-Meeting.md

This pull request contains the minutes of the January 2022 board meeting. Please let me know if everything is in order :)

Minutes of the last board meeting

---

_layouts/projects.html
_layouts/tutorials.html
_sass/mei.scss
index.html

This PR fixes the margins of header and content of the website on small devices as mentioned in #129 .
Fixes #129

fix(layout): align page margins of header and content

---

community/interest-groups.md

Change the spelling of "Neume" to "Neumes".

Change "Neume" to "Neumes"

---

resources/pedagogy.md

One of our co-admins changed so I updated the name on this page.

Updated co-administrator name

---

resources/pedagogy.md

We would like to include a list of events that occur annually and include music encoding pedagogy on this page.

added recurring pedagogical events

---

resources/pedagogy.md

Replaced the bibbase script with a regular list, because it does not play well when there is another bibbase script already on the page.

added simple list for recurring events

---

conference/awards.md

Title was missing on awards page.

Add title to awards page

---

.github/workflows/link-checker.yml

This PR adjusts the linkChecker workflow to the new lychee output since update to version 1.5.2 of lychee action: https://github.com/lycheeverse/lychee-action#readme
Fixes #399

Fix(gh-actions): update linkChecker workflow

---

_includes/head.html
index.html
js/carousel.js

The carousel on the index page was static, only showing other slides on active user interaction. With this commit, a 3s interval will be applied to automatically leaf through the slides.

Add animation for index page carousel

---

CONTRIBUTING.md

This PR adds a description of how to build and run the website using a docker image.

Feature: add description for local building and testing with docker

---

community/mei-board.md

This is still a draft, especially as @annplaksin and @musicog still should review their affiliations, AND of course it should only be merged after 2022

Update mei-board members for 2023

---

community/technical-team.md

This PR adds the ODD meeting dates for 2023.

Update ODD meetings

---

_posts/2022-06-06-teaching-music-history-session.md
community/mei-board/elections/2021/candidates.md

This PR fixes the latest broken links.
Closes #428 
Closes #426

Fix(website): fix broken links

---

_posts/2023-02-22-mec-tei2023.md

Updated info about the MEC/TEI Conference

update MEC-TEI conference

---

_conferences/2021/index.html
_conferences/2022/index.html
_conferences/2023/index.html
_config.yml

Please review - pulled in image from the TEI conference page (check to see if this will work)

Created conference landing page

---

_posts/2023-03-15-cfp-pedagogy-ig

Would like to add news item about Pedagogy IG CfP for resources

Add post for pedagogy IG cfp

---

.github/workflows/link-checker.yml

This PR updates the lychee action to the latest release which should include a fix for the verbosity issue mentioned in #444.

fix(ci): Update lychee-action to v1.7.0

---

_projects/rebalancing-music-canon.md
lychee.toml

Since link checker is running again correctly now, it recognized some broken links. This PR fixes these links reported in #455.
Fixes #455.

Fix broken links

---

_projects/beggars-opera.md

New project page created for the Beggar's Opera project.

new project page

---

_posts/2023-09-25-mei-5-released.md

Adds a news story for MEI 5.0. Mostly copied / pasted from the announcement e-mail.

News: MEI 5.0 released

---

_posts/2023-09-25-mec2024.md

created news update for MEC 2024 @bwbohl

news update for mec 2024

---

_posts/2023-09-07-mei-5-released.md
community/technical-team.md

This PR corrects some dates on the MEI website, just for my inner and future historian. ;)

Correct some dates

---

resources/mei_bibliography.bib

This PR adds two of the latest MEI related publications.

Add latest MEI related publications

---

lychee.toml

Add Twitter/X exclusion to linkchecker

---

community/technical-team.md

This PR updates the outdated ODD project link on the technical team page.
Thanks to @krHero for spotting.

Update outdated ODD project link

---

_conferences/2023/index.html

using a (smaller) version without the text to better fit the card header – as proposed by @musicEnfanthen in #591
NB, I did not update the json+ld image URL on purpose (since I think the full logo makes sense there) but will align those URLs if told so

Update teimec2023 logo

---

.github/workflows/jekyll.yml

Recreated PR #609 to target the correct (main) branch, and avoid line ending conflict. 
@rettinghaus When I create the commit via GH UI, the "preview" window shows me a single changed line 5. It is only by PR creation on GH, that the end of line gets automatically removed. I have now recreated the PR locally, and it seems to be OK now?
Fixes #608

Do only update on main (II)

---

_conferences/2024/program.html

@musicEnfanthen or @bwbohl  I updated the conference program with the schedule. Please review and merge if there are no issues.

MEC2024: added program details

---

_posts/2024-05-06-mec2024.md

Update created for MEC 2024 conference in news section

Posts: create 2024-05-06-mec2024.md

---

_conferences/2024/program.html

Updated conference program details.
Added bio to closing keynote and workshop descriptions.

MEC2024: Update program.html

---

index.html

remove sponsors section from index

---

community/interest-groups.md

New Co-Chair on agreement by @music-encoding/ig-metadata

Update chair of ig-metadata

---

CONTRIBUTING.md

This fixes a small typo in CONTRIBUTING.md. 
Also it includes a minor update to the checkout action.

doc(contributing): fix typo

---

community/technical-team.md

This PR updates the meeting time for the upcoming ODD meetings.

fix(community): update time for ODD meetings

---

_conferences/2014/index.html

State abbreviation was incorrect.

Typo corrected

---

_conferences/2025/index.html
_config.yml

Add 2025 conference landing page/placeholder 

---

community/technical-team.md

This PR updates the time schedule for the ODD meetings.

fix(technical team): update ODD meetings

---

conference/mec_proceedings.bib

This PR updates the conference proceedings bib file with the 2024 contributions.
Co-authored by @annakijas1

fix(proceedings): add entries for 2024

---

_conferences/2025/01_index.html
_conferences/2025/02_call.html

Hi, can someone please have a quick look before merging?

Added submission details to MEC 2025 call

---

_includes/header.html

remove twitter link and add title attributes

---

community/mei-board.md

This PR updates the board members for the new term and fixes the links to the meeting minutes.

fix(board): update board members and fix links

---

community/technical-team.md

This PR adds the schedule for the ODD meetings in 2025.

fix(technical-team): update ODD meetings

---

archive/comparison-v5_1.md
resources/schemas.md

This PR udpates the schemas page to include all files for MEI v5.1 and adds the corresponding comparison file.

guidelines: add MEI v5.1

---

_conferences/2025/07_program.html

A few corrections that @lpugin and some that I noticed.

MEC program corrections

---

_conferences/2025/02_program.html

Updated authors and institutions in the Conference Programme

MEC 2025: Update Conference Programme

---

_conferences/2025/02_program.html

* Add session chairs
* Update author list

MEC 2025: Update programme
